travis:
  secure:
    BINSTAR_TOKEN: HJnAPhhkOsxKtSlghXEVnWSsQ4lb3COqmfS4dXa44d3BKk8Vny82QbEtA8waChCuq0NysTHGsRNQnKhZEflRvjzB36pWVf/e+Rlsxufi4I7qDdjmf0BPzczbp02f/h0DBoA32M0tMh76Bngzcrp8eQSiUiDbN2QofxDm/J3eg8U7guGGpylYss/dZTF2miADkPSLoHs2rvIEiHBNbNKc37IpPmeNaZ6S1qFcQdkFd5RRGFsc61AP6CcT7yaQKbBzccK/+lfQ7N9RinRBKzEo+L396GRaBERuuXmom/k/C56d2/Ww+1s/uYpn35mWlYWJBD/xndPiJ/zK4R2Z8up/5ttmAe4I/MITNHmrcH93JcfLkcY0j0XP59NMCrhU3FT0wwLVSjc5CWLh9Ra80eFNdZQSp/R06JKi2ehj0Kh8TGO17rpVoCNpjpRUhIzWNlkCNs9A7HpMXoH69zDA/HBY8MabDmEgXEz0keSmtVkTZeW9XqD5q/oiJFxkXaxKZQVZNzF0nSF3sUhHzUUBFhyt+pL1zE/bt3Du4JmI76P+RXSQWxWCEhWeqHnVG88YRzcdFayN7+CXtR38gT+oDOaC90ihDlq96Nrwo+jgB5SdCQsDrrtgMPMzg2TugPN4Kkh4HoeDRdXvqGj/e1/FDmRzCwHsi/Xj0zlcC+BPOKdefGg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
